# -*- coding: utf-8 -*-

import re

DIVOFF_DIR = '/home/dawid/Repos/divinum-officium/web/www/horas/Polski/'

EXCLUDE_SECTIONS = (
    'Evangelium1',
    'Evangelium2',
    'Evangelium3',
    'Evangelium4',
    'Lectio1',
    'Prelude(rubrica 1570)',
    'Rank1570',
    'Rank1960',
    'RankNewcal',
    'RankTrident',
    'Rank',
    'Rank (rubrica 1955 aut rubrica 1960)',
    'Rank (rubrica 1960)',
    'Rank (rubrica innovata)',
    'Rank (si rubrica 1960)',
    'Rank (si rubrica innovata)',
    'Rule',
    'Tractus1',
    'Munda Cor Passionis',
    'GradualeF',
    'Responsory1',
    'Responsory2',
    'Responsory3',
    'Responsory4',
    'Responsory5',
    'Responsory6',
    'Responsory7',
    'Responsory8',
    'Lectio1',
    'Lectio2',
    'Lectio3',
)
EXCLUDE_SECTIONS_TITLES = (
    'Commemoratio Oratio',
    'Commemoratio Postcommunio',
    'Commemoratio Secreta',
    'Comment',
    'Prelude',
    'Prelude(rubrica 1960)',
    'Maundi',
    'Post Missam'
)


TRANSLATION = {
'Communicantes': 'Communicantes',
'CommunioP': 'Antyfona na Komunię (Okres Wielkanocny)',
'Communio': 'Antyfona na Komunię',
'Evangelium': 'Ewangelia',
'GradualeP': 'Alleluja Wielkanocne',
'Graduale': 'Graduał',
'Introitus': 'Introit',
'Lectio': 'Lekcja',
'OffertoriumP': 'Antyfona na Ofiarowanie (Okres Wielkanocny)',
'Offertorium': 'Antyfona na Ofiarowanie',
'Oratio': 'Kolekta',
'Postcommunio': 'Pokomunia',
'Secreta': 'Sekreta',
'Sequentia': 'Sekwencja',
'Super populum': 'Modlitwa nad ludem',
'Prefatio': 'Prefacja',
'Tractus': 'Traktus'}

TRANSLATION_MULTI = {
'GradualeL1': '1 Graduał',
'GradualeL2': '2 Graduał',
'GradualeL3': '3 Graduał',
'GradualeL4': '4 Graduał',
'GradualeL5': '5 Graduał',
'Graduale': '6 Graduał',
'LectioL1': '1 Lekcja',
'LectioL2': '2 Lekcja',
'LectioL3': '3 Lekcja',
'LectioL4': '4 Lekcja',
'LectioL5': '5 Lekcja',
'Lectio': '6 Lekcja',
'OratioL1': '2 Kolekta',
'OratioL2': '3 Kolekta',
'OratioL3': '4 Kolekta',
'OratioL4': '5 Kolekta',
'OratioL5': '6 Kolekta',
'Oratio': '1 Kolekta'}

PATERNOSTER = "Ojcze nasz, któryś jest w niebie: Święć się Imię Twoje, Przyjdź królestwo Twoje, Bądź wola Twoja jako w niebie tak i na ziemi.\nChleba naszego powszedniego daj nam dzisiaj I odpuść nam nasze winy, jako i my odpuszczamy naszym winowajcom. I nie wódź nas na pokuszenie. Ale nas zbaw ode złego. Amen."

REF_REGEX = re.compile('^@(.*):(.*)')
SECTION_REGEX = re.compile(r'^### *(.*)')

TRANSFORMATIONS = (
    (re.compile(r'\+\+'), '☩'),
    (re.compile(r'\+'), '☩'),
    (re.compile(r'^#'), '##'),
    (re.compile(r'^!x!'), '!'),
    (re.compile(r'^!! *(.*)'), '### \\1'),
    (re.compile(r'^\[([^\]]*)\]'), '### \\1'),
    (re.compile(r'^! *(.*)'), '*\\1*'),
    (re.compile(r'^v\. *'), ''),
    (re.compile(r'^_'), ''),
    (re.compile(r'\(\('), '('),
    (re.compile(r'\)\)'), ')'),
    (re.compile(r'\['), '('),
    (re.compile(r'\]'), ')'),
    (re.compile(r'^.*`.*$'), ''),
    (re.compile(r'^[&$]Gloria.*'), 'Chwała Ojcu.'),
    (re.compile(r'^\$Per Dominum.*'), 'Przez Pana.'),
    (re.compile(r'^\$Per eu[mn]dem.*'), 'Przez tegoż Pana.'),
    (re.compile(r'^\$Qui tecum.*'), 'Który z Tobą.'),
    (re.compile(r'^\$Qui vivis.*'), 'Który żyjesz.'),
    (re.compile(r'^\$Deo [Gg]ratias.*'), 'Bogu dzięki.'),
    (re.compile(r'^[&$]Dominus *[Vv]obiscum.*'), 'V. Pan z wami.    \n\rR. I z duchem twoim.'),
    (re.compile(r'^\*Modlitwa nad ludem\*.*'), ''),
    (re.compile(r'^\$Pater noster.*'), PATERNOSTER),
    (re.compile(r'\(rubrica 1955 aut rubrica 1960 dicitur\)'), ''),
    (re.compile(r'\(deinde dicuntur semper\)'), ''),
)

PROPERS_INPUT = (
('Adwent',),
('Tempora/Adv1-0.txt'),
('Tempora/Adv1-1.txt'),
('Tempora/Adv1-2.txt'),
('Tempora/Adv1-3.txt'),
('Tempora/Adv1-4.txt'),
('Tempora/Adv1-5.txt'),
('Tempora/Adv1-6.txt'),
('Tempora/Adv2-0.txt'),
('Tempora/Adv2-1.txt'),
('Tempora/Adv2-2.txt'),
('Tempora/Adv2-3.txt'),
('Tempora/Adv2-4.txt'),
('Tempora/Adv2-5.txt'),
('Tempora/Adv2-6.txt'),
('Tempora/Adv3-0.txt'),
('Tempora/Adv3-1.txt'),
('Tempora/Adv3-2.txt'),
('Tempora/Adv3-3.txt'),
('Tempora/Adv3-4.txt'),
('Tempora/Adv3-5.txt'),
('Tempora/Adv3-6.txt'),
('Tempora/Adv4-0.txt'),
('Tempora/Adv4-1.txt'),
('Tempora/Adv4-2.txt'),
('Tempora/Adv4-3.txt'),
('Tempora/Adv4-4.txt'),
('Tempora/Adv4-5.txt'),


('Boże Narodzenie',),
('Tempora/Nat1-0.txt'),
('Tempora/Nat2-0.txt'),

('Okres po Objawieniu',),
('Tempora/Epi1-0.txt'),
('Tempora/Epi1-1.txt'),
('Tempora/Epi1-2.txt'),
('Tempora/Epi1-3.txt'),
('Tempora/Epi1-4.txt'),
('Tempora/Epi1-5.txt'),
('Tempora/Epi1-6.txt'),
('Tempora/Epi2-0.txt'),
('Tempora/Epi2-1.txt'),
('Tempora/Epi2-2.txt'),
('Tempora/Epi2-3.txt'),
('Tempora/Epi2-4.txt'),
('Tempora/Epi2-5.txt'),
('Tempora/Epi2-6.txt'),
('Tempora/Epi3-0.txt'),
('Tempora/Epi3-1.txt'),
('Tempora/Epi3-2.txt'),
('Tempora/Epi3-3.txt'),
('Tempora/Epi3-4.txt'),
('Tempora/Epi3-5.txt'),
('Tempora/Epi3-6.txt'),
('Tempora/Epi4-0.txt'),
('Tempora/Epi4-1.txt'),
('Tempora/Epi4-2.txt'),
('Tempora/Epi4-3.txt'),
('Tempora/Epi4-4.txt'),
('Tempora/Epi4-5.txt'),
('Tempora/Epi4-6.txt'),
('Tempora/Epi5-0.txt'),
('Tempora/Epi5-1.txt'),
('Tempora/Epi5-2.txt'),
('Tempora/Epi5-3.txt'),
('Tempora/Epi5-4.txt'),
('Tempora/Epi5-5.txt'),
('Tempora/Epi5-6.txt'),
('Tempora/Epi6-0.txt'),
('Tempora/Epi6-1.txt'),
('Tempora/Epi6-2.txt'),
('Tempora/Epi6-3.txt'),
('Tempora/Epi6-4.txt'),
('Tempora/Epi6-5.txt'),
('Tempora/Epi6-6.txt'),

('Przedpoście',),
('Tempora/Quadp1-0.txt'),
('Tempora/Quadp1-1.txt'),
('Tempora/Quadp1-2.txt'),
('Tempora/Quadp1-3.txt'),
('Tempora/Quadp1-4.txt'),
('Tempora/Quadp1-5.txt'),
('Tempora/Quadp1-6.txt'),
('Tempora/Quadp2-0.txt'),
('Tempora/Quadp2-1.txt'),
('Tempora/Quadp2-2.txt'),
('Tempora/Quadp2-3.txt'),
('Tempora/Quadp2-4.txt'),
('Tempora/Quadp2-5.txt'),
('Tempora/Quadp2-6.txt'),
('Tempora/Quadp3-0.txt'),
('Tempora/Quadp3-1.txt'),
('Tempora/Quadp3-2.txt'),
('Tempora/Quadp3-3.txt'),
('Tempora/Quadp3-4.txt'),
('Tempora/Quadp3-5.txt'),
('Tempora/Quadp3-6.txt'),
('Tempora/Quadp1-0.txt'),
('Tempora/Quadp1-1.txt'),
('Tempora/Quadp1-2.txt'),
('Tempora/Quadp1-3.txt'),
('Tempora/Quadp1-4.txt'),
('Tempora/Quadp1-5.txt'),
('Tempora/Quadp1-6.txt'),
('Tempora/Quadp2-0.txt'),
('Tempora/Quadp2-1.txt'),
('Tempora/Quadp2-2.txt'),
('Tempora/Quadp2-3.txt'),
('Tempora/Quadp2-4.txt'),
('Tempora/Quadp2-5.txt'),
('Tempora/Quadp2-6.txt'),
('Tempora/Quadp3-0.txt'),
('Tempora/Quadp3-1.txt'),
('Tempora/Quadp3-2.txt'),
('Tempora/Quadp3-3.txt'),
('Tempora/Quadp3-4.txt'),
('Tempora/Quadp3-5.txt'),
('Tempora/Quadp3-6.txt'),

('Wielki Post',),
('Tempora/Quad1-0.txt'),
('Tempora/Quad1-1.txt'),
('Tempora/Quad1-2.txt'),
('Tempora/Quad1-3.txt'),
('Tempora/Quad1-4.txt'),
('Tempora/Quad1-5.txt'),
('Tempora/Quad1-6.txt'),
('Tempora/Quad2-0.txt'),
('Tempora/Quad2-1.txt'),
('Tempora/Quad2-2.txt'),
('Tempora/Quad2-3.txt'),
('Tempora/Quad2-4.txt'),
('Tempora/Quad2-5.txt'),
('Tempora/Quad2-6.txt'),
('Tempora/Quad3-0.txt'),
('Tempora/Quad3-1.txt'),
('Tempora/Quad3-2.txt'),
('Tempora/Quad3-3.txt'),
('Tempora/Quad3-4.txt'),
('Tempora/Quad3-5.txt'),
('Tempora/Quad3-6.txt'),
('Tempora/Quad4-0.txt'),
('Tempora/Quad4-1.txt'),
('Tempora/Quad4-2.txt'),
('Tempora/Quad4-3.txt'),
('Tempora/Quad4-4.txt'),
('Tempora/Quad4-5.txt'),
('Tempora/Quad4-6.txt'),
('Tempora/Quad5-0.txt'),
('Tempora/Quad5-1.txt'),
('Tempora/Quad5-2.txt'),
('Tempora/Quad5-3.txt'),
('Tempora/Quad5-4.txt'),
('Tempora/Quad5-5Feriat.txt'),
('Tempora/Quad5-5Feria.txt'),
('Tempora/Quad5-5.txt'),
('Tempora/Quad5-6.txt'),
('Tempora/Quad6-0r.txt'),
('Tempora/Quad6-0.txt'),
('Tempora/Quad6-1.txt'),
('Tempora/Quad6-2.txt'),
('Tempora/Quad6-3.txt'),
('Tempora/Quad6-4r.txt'),
('Tempora/Quad6-4.txt'),
('Tempora/Quad6-5r.txt'),
('Tempora/Quad6-5.txt'),
('Tempora/Quad6-6r.txt'),
('Tempora/Quad6-6.txt'),

('Okres Wielkanocny',),
('Tempora/Pasc0-0.txt'),
('Tempora/Pasc0-1.txt'),
('Tempora/Pasc0-2.txt'),
('Tempora/Pasc0-3.txt'),
('Tempora/Pasc0-4.txt'),
('Tempora/Pasc0-5.txt'),
('Tempora/Pasc0-6.txt'),
('Tempora/Pasc1-0.txt'),
('Tempora/Pasc1-1.txt'),
('Tempora/Pasc1-2.txt'),
('Tempora/Pasc1-3.txt'),
('Tempora/Pasc1-4.txt'),
('Tempora/Pasc1-5.txt'),
('Tempora/Pasc1-6.txt'),
('Tempora/Pasc2-0.txt'),
('Tempora/Pasc2-1.txt'),
('Tempora/Pasc2-2.txt'),
('Tempora/Pasc2-3Feria.txt'),
('Tempora/Pasc2-3.txt'),
('Tempora/Pasc2-4Feria.txt'),
('Tempora/Pasc2-4.txt'),
('Tempora/Pasc2-5Feria.txt'),
('Tempora/Pasc2-5.txt'),
('Tempora/Pasc2-6Feria.txt'),
('Tempora/Pasc2-6.txt'),
('Tempora/Pasc3-0r.txt'),
('Tempora/Pasc3-0t.txt'),
('Tempora/Pasc3-0.txt'),
('Tempora/Pasc3-1Feria.txt'),
('Tempora/Pasc3-1.txt'),
('Tempora/Pasc3-2Feria.txt'),
('Tempora/Pasc3-2.txt'),
('Tempora/Pasc3-3Feria.txt'),
('Tempora/Pasc3-3.txt'),
('Tempora/Pasc3-4.txt'),
('Tempora/Pasc3-5.txt'),
('Tempora/Pasc3-6.txt'),
('Tempora/Pasc4-0.txt'),
('Tempora/Pasc4-1.txt'),
('Tempora/Pasc4-2.txt'),
('Tempora/Pasc4-3.txt'),
('Tempora/Pasc4-4.txt'),
('Tempora/Pasc4-5.txt'),
('Tempora/Pasc4-6.txt'),
('Tempora/Pasc5-0.txt'),
('Tempora/Pasc5-1r.txt'),
('Tempora/Pasc5-1.txt'),
('Tempora/Pasc5-2.txt'),
('Tempora/Pasc5-3.txt'),
('Tempora/Pasc5-4.txt'),
('Tempora/Pasc5-5.txt'),
('Tempora/Pasc5-6.txt'),
('Tempora/Pasc6-0.txt'),
('Tempora/Pasc6-1.txt'),
('Tempora/Pasc6-2.txt'),
('Tempora/Pasc6-3.txt'),
('Tempora/Pasc6-4.txt'),
('Tempora/Pasc6-5.txt'),
('Tempora/Pasc6-6.txt'),
('Tempora/Pasc7-0.txt'),
('Tempora/Pasc7-1.txt'),
('Tempora/Pasc7-2.txt'),
('Tempora/Pasc7-3.txt'),
('Tempora/Pasc7-4.txt'),
('Tempora/Pasc7-5.txt'),
('Tempora/Pasc7-6.txt'),

('Okres po Zesłaniu',),
('Tempora/Pent01-0r.txt'),
('Tempora/Pent01-0.txt'),
('Tempora/Pent01-1.txt'),
('Tempora/Pent01-2.txt'),
('Tempora/Pent01-3.txt'),
('Tempora/Pent01-4.txt'),
('Tempora/Pent01-5.txt'),
('Tempora/Pent01-6.txt'),
('Tempora/Pent02-0.txt'),
('Tempora/Pent02-1.txt'),
('Tempora/Pent02-2.txt'),
('Tempora/Pent02-3.txt'),
('Tempora/Pent02-4.txt'),
('Tempora/Pent02-5Feria.txt'),
('Tempora/Pent02-5.txt'),
('Tempora/Pent02-6Feria.txt'),
('Tempora/Pent02-6.txt'),
('Tempora/Pent03-0o.txt'),
('Tempora/Pent03-0r.txt'),
('Tempora/Pent03-0.txt'),
('Tempora/Pent03-1Feriao.txt'),
('Tempora/Pent03-1Feria.txt'),
('Tempora/Pent03-1.txt'),
('Tempora/Pent03-2Feriao.txt'),
('Tempora/Pent03-2Feria.txt'),
('Tempora/Pent03-2.txt'),
('Tempora/Pent03-3Feria.txt'),
('Tempora/Pent03-3.txt'),
('Tempora/Pent03-4Feria.txt'),
('Tempora/Pent03-4.txt'),
('Tempora/Pent03-5Feriao.txt'),
('Tempora/Pent03-5Feria.txt'),
('Tempora/Pent03-5.txt'),
('Tempora/Pent03-6o.txt'),
('Tempora/Pent03-6.txt'),
('Tempora/Pent04-0o.txt'),
('Tempora/Pent04-0.txt'),
('Tempora/Pent04-1o.txt'),
('Tempora/Pent04-1.txt'),
('Tempora/Pent04-2o.txt'),
('Tempora/Pent04-2.txt'),
('Tempora/Pent04-3o.txt'),
('Tempora/Pent04-3.txt'),
('Tempora/Pent04-4o.txt'),
('Tempora/Pent04-4.txt'),
('Tempora/Pent04-5o.txt'),
('Tempora/Pent04-5.txt'),
('Tempora/Pent04-6.txt'),
('Tempora/Pent05-0o.txt'),
('Tempora/Pent05-0.txt'),
('Tempora/Pent05-1.txt'),
('Tempora/Pent05-2.txt'),
('Tempora/Pent05-3.txt'),
('Tempora/Pent05-4.txt'),
('Tempora/Pent05-5.txt'),
('Tempora/Pent05-6.txt'),
('Tempora/Pent06-0.txt'),
('Tempora/Pent06-1.txt'),
('Tempora/Pent06-2.txt'),
('Tempora/Pent06-3.txt'),
('Tempora/Pent06-4.txt'),
('Tempora/Pent06-5.txt'),
('Tempora/Pent06-6.txt'),
('Tempora/Pent07-0.txt'),
('Tempora/Pent07-1.txt'),
('Tempora/Pent07-2.txt'),
('Tempora/Pent07-3.txt'),
('Tempora/Pent07-4.txt'),
('Tempora/Pent07-5.txt'),
('Tempora/Pent07-6.txt'),
('Tempora/Pent08-0.txt'),
('Tempora/Pent08-1.txt'),
('Tempora/Pent08-2.txt'),
('Tempora/Pent08-3.txt'),
('Tempora/Pent08-4.txt'),
('Tempora/Pent08-5.txt'),
('Tempora/Pent08-6.txt'),
('Tempora/Pent09-0.txt'),
('Tempora/Pent09-1.txt'),
('Tempora/Pent09-2.txt'),
('Tempora/Pent09-3.txt'),
('Tempora/Pent09-4.txt'),
('Tempora/Pent09-5.txt'),
('Tempora/Pent09-6.txt'),
('Tempora/Pent10-0.txt'),
('Tempora/Pent10-1.txt'),
('Tempora/Pent10-2.txt'),
('Tempora/Pent10-3.txt'),
('Tempora/Pent10-4.txt'),
('Tempora/Pent10-5.txt'),
('Tempora/Pent10-6.txt'),
('Tempora/Pent11-0.txt'),
('Tempora/Pent11-1.txt'),
('Tempora/Pent11-2.txt'),
('Tempora/Pent11-3.txt'),
('Tempora/Pent11-4.txt'),
('Tempora/Pent11-5.txt'),
('Tempora/Pent11-6.txt'),
('Tempora/Pent12-0.txt'),
('Tempora/Pent12-1.txt'),
('Tempora/Pent12-2.txt'),
('Tempora/Pent12-3.txt'),
('Tempora/Pent12-4.txt'),
('Tempora/Pent12-5.txt'),
('Tempora/Pent12-6.txt'),
('Tempora/Pent13-0.txt'),
('Tempora/Pent13-1.txt'),
('Tempora/Pent13-2.txt'),
('Tempora/Pent13-3.txt'),
('Tempora/Pent13-4.txt'),
('Tempora/Pent13-5.txt'),
('Tempora/Pent13-6.txt'),
('Tempora/Pent14-0.txt'),
('Tempora/Pent14-1.txt'),
('Tempora/Pent14-2.txt'),
('Tempora/Pent14-3.txt'),
('Tempora/Pent14-4.txt'),
('Tempora/Pent14-5.txt'),
('Tempora/Pent14-6.txt'),
('Tempora/Pent15-0.txt'),
('Tempora/Pent15-1.txt'),
('Tempora/Pent15-2.txt'),
('Tempora/Pent15-3.txt'),
('Tempora/Pent15-4.txt'),
('Tempora/Pent15-5.txt'),
('Tempora/Pent15-6.txt'),
('Tempora/Pent16-0.txt'),
('Tempora/Pent16-1.txt'),
('Tempora/Pent16-2.txt'),
('Tempora/Pent16-3.txt'),
('Tempora/Pent16-4.txt'),
('Tempora/Pent16-5.txt'),
('Tempora/Pent16-6.txt'),
('Tempora/Pent17-0.txt'),
('Tempora/Pent17-1.txt'),
('Tempora/Pent17-2.txt'),
('Tempora/Pent17-3.txt'),
('Tempora/Pent17-4.txt'),
('Tempora/Pent17-5.txt'),
('Tempora/Pent17-6.txt'),
('Tempora/Pent18-0.txt'),
('Tempora/Pent18-1.txt'),
('Tempora/Pent18-2.txt'),
('Tempora/Pent18-3.txt'),
('Tempora/Pent18-4.txt'),
('Tempora/Pent18-5.txt'),
('Tempora/Pent18-6.txt'),
('Tempora/Pent19-0.txt'),
('Tempora/Pent19-1.txt'),
('Tempora/Pent19-2.txt'),
('Tempora/Pent19-3.txt'),
('Tempora/Pent19-4.txt'),
('Tempora/Pent19-5.txt'),
('Tempora/Pent19-6.txt'),
('Tempora/Pent20-0.txt'),
('Tempora/Pent20-1.txt'),
('Tempora/Pent20-2.txt'),
('Tempora/Pent20-3.txt'),
('Tempora/Pent20-4.txt'),
('Tempora/Pent20-5.txt'),
('Tempora/Pent20-6.txt'),
('Tempora/Pent21-0.txt'),
('Tempora/Pent21-1.txt'),
('Tempora/Pent21-2.txt'),
('Tempora/Pent21-3.txt'),
('Tempora/Pent21-4.txt'),
('Tempora/Pent21-5.txt'),
('Tempora/Pent21-6.txt'),
('Tempora/Pent22-0.txt'),
('Tempora/Pent22-1.txt'),
('Tempora/Pent22-2.txt'),
('Tempora/Pent22-3.txt'),
('Tempora/Pent22-4.txt'),
('Tempora/Pent22-5.txt'),
('Tempora/Pent22-6.txt'),
('Tempora/Pent23-0.txt'),
('Tempora/Pent23-1.txt'),
('Tempora/Pent23-2.txt'),
('Tempora/Pent23-3.txt'),
('Tempora/Pent23-4.txt'),
('Tempora/Pent23-5.txt'),
('Tempora/Pent23-6.txt'),
('Tempora/Pent24-0.txt'),
('Tempora/Pent24-1.txt'),
('Tempora/Pent24-2.txt'),
('Tempora/Pent24-3.txt'),
('Tempora/Pent24-4.txt'),
('Tempora/Pent24-5.txt'),
('Tempora/Pent24-6.txt'),


('Inne',),
('Tempora/081-0.txt'),
('Tempora/081-1.txt'),
('Tempora/081-2.txt'),
('Tempora/081-3.txt'),
('Tempora/081-4.txt'),
('Tempora/081-5.txt'),
('Tempora/081-6.txt'),
('Tempora/082-0.txt'),
('Tempora/082-1.txt'),
('Tempora/082-2.txt'),
('Tempora/082-3.txt'),
('Tempora/082-4.txt'),
('Tempora/082-5.txt'),
('Tempora/082-6.txt'),
('Tempora/083-0.txt'),
('Tempora/083-1.txt'),
('Tempora/083-2.txt'),
('Tempora/083-3.txt'),
('Tempora/083-4.txt'),
('Tempora/083-5.txt'),
('Tempora/083-6.txt'),
('Tempora/084-0.txt'),
('Tempora/084-1.txt'),
('Tempora/084-2.txt'),
('Tempora/084-3.txt'),
('Tempora/084-4.txt'),
('Tempora/084-5.txt'),
('Tempora/084-6.txt'),
('Tempora/085-0.txt'),
('Tempora/085-1.txt'),
('Tempora/085-2.txt'),
('Tempora/085-3.txt'),
('Tempora/085-4.txt'),
('Tempora/085-5.txt'),
('Tempora/085-6.txt'),
('Tempora/091-0.txt'),
('Tempora/091-1.txt'),
('Tempora/091-2.txt'),
('Tempora/091-3.txt'),
('Tempora/091-4.txt'),
('Tempora/091-5.txt'),
('Tempora/091-6.txt'),
('Tempora/092-0.txt'),
('Tempora/092-1.txt'),
('Tempora/092-2.txt'),
('Tempora/092-3.txt'),
('Tempora/092-4.txt'),
('Tempora/092-5.txt'),
('Tempora/092-6.txt'),
('Tempora/093-0.txt'),
('Tempora/093-1.txt'),
('Tempora/093-2.txt'),
('Tempora/093-3.txt'),
('Tempora/093-4.txt'),
('Tempora/093-5.txt'),
('Tempora/093-6.txt'),
('Tempora/094-0.txt'),
('Tempora/094-1.txt'),
('Tempora/094-2.txt'),
('Tempora/094-3.txt'),
('Tempora/094-4.txt'),
('Tempora/094-5.txt'),
('Tempora/094-6.txt'),
('Tempora/095-0.txt'),
('Tempora/095-1.txt'),
('Tempora/095-2.txt'),
('Tempora/095-3.txt'),
('Tempora/095-4.txt'),
('Tempora/095-5.txt'),
('Tempora/095-6.txt'),
('Tempora/101-0.txt'),
('Tempora/101-1.txt'),
('Tempora/101-2.txt'),
('Tempora/101-3.txt'),
('Tempora/101-4.txt'),
('Tempora/101-5.txt'),
('Tempora/101-6.txt'),
('Tempora/102-0.txt'),
('Tempora/102-1.txt'),
('Tempora/102-2.txt'),
('Tempora/102-3.txt'),
('Tempora/102-4.txt'),
('Tempora/102-5.txt'),
('Tempora/102-6.txt'),
('Tempora/103-0.txt'),
('Tempora/103-1.txt'),
('Tempora/103-2.txt'),
('Tempora/103-3.txt'),
('Tempora/103-4.txt'),
('Tempora/103-5.txt'),
('Tempora/103-6.txt'),
('Tempora/104-0.txt'),
('Tempora/104-1.txt'),
('Tempora/104-2.txt'),
('Tempora/104-3.txt'),
('Tempora/104-4.txt'),
('Tempora/104-5.txt'),
('Tempora/104-6.txt'),
('Tempora/105-0.txt'),
('Tempora/105-1.txt'),
('Tempora/105-2.txt'),
('Tempora/105-3.txt'),
('Tempora/105-4.txt'),
('Tempora/105-5.txt'),
('Tempora/105-6.txt'),
('Tempora/111-0.txt'),
('Tempora/111-1.txt'),
('Tempora/111-2.txt'),
('Tempora/111-3.txt'),
('Tempora/111-4.txt'),
('Tempora/111-5.txt'),
('Tempora/111-6.txt'),
('Tempora/112-0.txt'),
('Tempora/112-1.txt'),
('Tempora/112-2.txt'),
('Tempora/112-3.txt'),
('Tempora/112-4.txt'),
('Tempora/112-5.txt'),
('Tempora/112-6.txt'),
('Tempora/113-0.txt'),
('Tempora/113-1.txt'),
('Tempora/113-2.txt'),
('Tempora/113-3.txt'),
('Tempora/113-4.txt'),
('Tempora/113-5.txt'),
('Tempora/113-6.txt'),
('Tempora/114-0.txt'),
('Tempora/114-1.txt'),
('Tempora/114-2.txt'),
('Tempora/114-3.txt'),
('Tempora/114-4.txt'),
('Tempora/114-5.txt'),
('Tempora/114-6.txt'),
('Tempora/115-0.txt'),
('Tempora/115-1.txt'),
('Tempora/115-2.txt'),
('Tempora/115-3.txt'),
('Tempora/115-4.txt'),
('Tempora/115-5.txt'),
('Tempora/115-6.txt'),
)
